title: "Curriculum Vitae"
description: "Julia Lamprecht //
PhD Student in Astronomy • Galaxy Dynamics • SMBHs • NSCs"
theme: jekyll-theme-cayman

lang: en

# Social
github_username: juliala2504
email: lamprecht@sci.muni.cz
